services:
  - type: web
    name: code-editor
    env: node
    buildCommand: |
      # Install Java during build phase
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk install java 11.0.19-tem
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JAVA_HOME
        value: /opt/render/.sdkman/candidates/java/current